formatter: markdown document

# Pin to major version 0, and allow minor/patch upgrades.
version: ~> 0.16

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules

sections:
  show:
    - all
  hide: []

# Available options with their default values.
content: ""

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->

    {{ .Content }}

    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: type

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
